"""Add operation_log table

Revision ID: 59cc1bb47a8c
Revises: ccdc1d8a6b8f
Create Date: 2025-06-15 09:42:45.385438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59cc1bb47a8c'
down_revision = 'ccdc1d8a6b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_time', sa.DateTime(), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_name', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.String(length=50), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_operation_time'), ['operation_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_operator_id'), ['operator_id'], unique=False)

    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.alter_column('lock_status',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='锁定状态',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.alter_column('lock_status',
               existing_type=mysql.TINYINT(display_width=1),
               comment='锁定状态',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_operator_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_operation_type'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_operation_time'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_object_type'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_object_id'))

    op.drop_table('operation_logs')
    # ### end Alembic commands ###
