"""add owner_id to product

Revision ID: ccdc1d8a6b8f
Revises: 722ba7bd9354
Create Date: 2025-06-14 15:36:02.974721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccdc1d8a6b8f'
down_revision = '722ba7bd9354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('name')
        batch_op.drop_index('roles_index_0')
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_index('users_index_0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('users_index_0', ['username', 'email'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_index('roles_index_0', ['name'], unique=False)
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
